# Generated by Django 3.2.4 on 2021-06-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0002_actor_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title_name',)},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='title_name',
        ),
    ]
